import Main from '../components/main';
import './global.css';
import { Manrope } from 'next/font/google';

export const metadata = {
  title: 'Welcome to store',
  description: 'Generated by create-nx-workspace',
};

const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-manrope',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${manrope.variable}`}>
      <body>
        <Main>{children}</Main>
      </body>
    </html>
  );
}
